matrix:
  include:
    - language: node_js
      node_js: 
        - "stable"
      dist: trusty
      install:
        - cd backend && npm install && cd ..
      script:
        - cd backend && npm test